### ISSUE TITLE
Cannot detect SCD30

### ISSUE THREAD

**Issue by mawmaw1** [postronium/SCD30-Raspberry-Pi#1]
Doing the steps in https://raspberrypi.stackexchange.com/questions/37796/how-to-use-i2c-gpio-with-raspberry-pi I still cannot detect the SCD30 using 'sudo i2cdetect -y 1' / 'sudo i2cdetect -y 3' . Do you have any advice? The pins should be connected correctly.

**Comment by mawmaw1** [comment]
Managed to detect it with i2c at 0x61. Getting IOError: [Errno 6] No such device or address.

Any suggestions?

**Comment by mawmaw1** [comment]
Changed the SMbus to (1) and getting data now, but it doesn't seem to change.
Also getting the following:
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    data = sensor.read_measurement()
  File "/home/pi/SCD30-Raspberry-Pi/src/scd30.py", line 183, in read_measurement
    floatData = numpy.array(data, dtype=numpy.int32)
OverflowError: Python int too large to convert to C long

**Comment by UtecRS** [comment]
Still struggling?

Does [this ](https://github.com/UnravelTEC/Raspi-Driver-SCD30) help?

Maybe @species can help

**Comment by mawmaw1** [comment]
@UtecRS 
Damn, could've used that library back then ;-) We figured it out, but has since moved to other projects. Thank you.
